### ISSUE TITLE
fix pub point problems

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_convenient_test#104]

**Comment by fzyzcjy** [comment]
0/10 points: Provide a valid pubspec.yaml
The package description is too short.
Add more detail to the description field of pubspec.yaml. Use 60 to 180 characters to describe the package, what it does, and its target use case.

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/167073215-33718587-be67-4423-9e26-6208f78731f2.png)

**Comment by fzyzcjy** [comment]
see https://pub.dev/my-packages

**Comment by fzyzcjy** [comment]
related #110

**Comment by fzyzcjy** [comment]
bump

**Comment by Rohithgilla12** [comment]
Can I work on it @fzyzcjy ?

**Comment by fzyzcjy** [comment]
Sure!

**Comment by fzyzcjy** [comment]
bump

**Comment by Rohithgilla12** [comment]
@fzyzcjy I was checking this

https://pub.dev/packages/convenient_test/score 
It is because of a formatting issue.

![image](https://user-images.githubusercontent.com/19389850/194048881-e6cd316c-d0c4-4fcb-ade6-df856e93e114.png)


I think it might be because we are using `{ "dart.lineLength": 120 }` but dart default is `80`.

**Comment by fzyzcjy** [comment]
@Rohithgilla12 Yes that is the problem.

**Comment by fzyzcjy** [comment]
bump
