### ISSUE TITLE
Manager: do not use functions that return widgets

### ISSUE THREAD

**Issue by gilice** [fzyzcjy/flutter_convenient_test#320]
This is bad practice, see:
- https://stackoverflow.com/questions/53234825/what-is-the-difference-between-functions-and-classes-to-create-r-eusable-widgets/53234826#53234826
https://github.com/flutter/flutter/issues/19269

What we should do:
- either codegen, for example with https://pub.dev/packages/functional_widget
- just convert them to stateless/stateful widgets
- use a [`Builder`](https://api.flutter.dev/flutter/widgets/Builder-class.html) widget 

@fzyzcjy I can do this, which would you prefer?

**Comment by fzyzcjy** [comment]
Hmm we are using `mobx` and thus `Observer`s. Observer is like Builder, and thus IMHO is not slow to do so.

**Comment by gilice** [comment]
While that is true, there are a TON of functions like 
`Widget _buildBody(BuildContext context) {`
over the code.
It is bad practice as you can see.

**Comment by fzyzcjy** [comment]
Yes I agree. I originally did that because of the simplicity it gives, since you know, convenient_test_manager runs on a desktop, thus this slowdown is never noticeable for humans ;)

Happy to hear that you like to contribute to the codebase! Maybe we can prioritize to work on more critical features first. For example, to have some new feature.

**Comment by gilice** [comment]
Hey!
I am currently working on the dark theme PR because a lot of colors were hardcoded.
If you give permission, I'd like to start a bigger project to refactor the UI a bit, for example
- no functions like this
- no hardcoded colors
- make it more responsive (see #321 )

I will try to make the diff as minimal as possible.
