### ISSUE TITLE
How can this be run on Github Actions?

### ISSUE THREAD

**Issue by tomadimitrie** [fzyzcjy/flutter_convenient_test#330]
Is there any way to run this on Github Actions? I can't find any documentation about headless running. 

I found some commands in #240, but they require 2 shells, should I just run the manager in the background?

Also, thank you for the package! It's really cool

**Comment by fzyzcjy** [comment]
Hi, you are welcome!

I have not personally run it on github actions, but it is theoretically possible, since the `worker` is nothing but a normal flutter integration test, and the `manager` is nothing but a normal Dart command line program (just like any command line program).

As for requiring 2 shells, what about, e.g. https://stackoverflow.com/questions/3004811/how-do-you-run-multiple-programs-in-parallel-from-a-bash-script

**Comment by fzyzcjy** [comment]
In addition, if your app is an Android/iOS one, you may refer to https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/.github/workflows/ci.yaml to see how flutter_rust_bridge uses CI to run Flutter's integration test. the worker part of flutter_convenient_test is just the same as integration test in terms of infra setup, and the manager (convenient_test_manager_dart) is nothing but a normal binary.
