### ISSUE TITLE
7 months is a long time, is there a release coming to work with flutter 3.10.x and dart 3 please

### ISSUE THREAD

**Issue by neiljaywarner** [fzyzcjy/flutter_convenient_test#341]
thanks so much :)

**Comment by fzyzcjy** [comment]
Sure! Firstly try to use master branch before releasing. Btw do you know that, new features have been added to the master branch ;) Mainly:

1. run the same test code using host machine without a simulator, much faster (e.g. 10x) and stabler
2. a simple yet useful monkey (to be open sourced)

Because of the new features, I hope I can find a bit of time to update README and then release the new version.

**Comment by ahmdt** [comment]
is this project dead?

**Comment by fzyzcjy** [comment]
NO! I use it personally everyday!

**Comment by fzyzcjy** [comment]
v1.3.0 is published :)
