### ISSUE TITLE
I'm a newbie, and I find that this is a library with bad documentation, I don't know where to start, it's just confusing.

### ISSUE THREAD

**Issue by vqh2602** [fzyzcjy/flutter_convenient_test#402]
I'm a newbie, and I find that this is a library with bad documentation, I don't know where to start, it's just confusing. When applied to a real project there are always errors, I have to swim in that pile of confusing and incomplete documents :))

**Comment by fzyzcjy** [comment]
Yes, I agree the doc is a bit lacking currently., because you know, it is really time-consuming on https://github.com/fzyzcjy/flutter_rust_bridge (and other open source libs)... 

Anyway, hope https://github.com/fzyzcjy/flutter_convenient_test/pull/399 will make the doc somehow easier (thanks to @madmini's contribution!)
